apiVersion: v1
kind: Namespace
metadata:
  name: service-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-pod
  namespace: service-system
spec:
  selector:
    matchLabels:
      app: go-service
  template:
    metadata:
      labels:
        app: go-service
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: service-api
        image: service-arm64:1.0
